version: '3.4'

services:
  ui:
    build:
      context: .
    restart: always
    environment:
      - VITE_GLOB_AUTHORITY=http://127.0.0.1:44385
    ports:
      - "40080:80"
    networks:
      - abp-next-admin

networks:
  abp-next-admin:
    driver: bridge

#整个目录作为上下文，但dockerfile copy只用到了dist和docker目录，应该改为只用需要的目录作为上下文，提高构建效率
#用.dockerignore文件定义排除的文件解决此问题